# Generated by Django 2.2.10 on 2020-06-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200616_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[('True', 'True'), ('False', 'False')]),
        ),
    ]
