# Generated by Django 2.2.10 on 2020-08-09 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mission',
            field=models.CharField(blank=True, choices=[('PAIE', 'Responsable_paiement'), ('CDE', 'Responsable_commende'), ('DEUX', 'Les_deux')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='releve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fac', models.DateField()),
                ('ref_fac', models.CharField(max_length=50)),
                ('mnt_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mnt_regler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_social', models.CharField(blank=True, max_length=30, null=True)),
                ('compte', models.CharField(blank=True, max_length=8, null=True)),
                ('nom_societe', models.CharField(blank=True, max_length=30, null=True)),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('catalog', models.BooleanField(default=False)),
                ('releve', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
