# Generated by Django 2.2.10 on 2020-08-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200809_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='releve',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
