# Generated by Django 2.2.10 on 2020-08-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_releve_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nom_societe',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
