# Generated by Django 2.2.10 on 2020-08-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_nom_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mission',
            field=models.CharField(blank=True, choices=[('PAIE', 'Responsable_paiement'), ('CDE', 'Responsable_commande'), ('DEUX', 'Les_deux')], max_length=10, null=True),
        ),
    ]
