# Generated by Django 2.2.10 on 2020-08-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200810_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepro',
            name='compte',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
