# Generated by Django 2.2.10 on 2020-08-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profilepro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepro',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
