# Generated by Django 2.2.10 on 2020-08-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_compte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='compte',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='compte',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
